// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://njdatkyuangmnznmmxwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZGF0a3l1YW5nbW56bm1teHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTkwMzEsImV4cCI6MjA2OTYzNTAzMX0.GjXwFDyaWLrRjH56HZfGOOhI5R__hlS_r156aV-a9WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);